include:
  - board: nice_nano_v2
    shield: charybdis_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: charybdis_right
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: settings_reset
